config/routes.rb
Rails.application.routes.draw do

  root :to => 'todo_lists#index'
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]

  get '/accounts' => "accounts#index", as: "accounts_path"
  get '/todo_lists' => "todo_lists#index", as: "todo_lists_path"
  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  has_and_belongs_to_many :tags

  default_scope { order due_date: :asc}
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list 
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # GET /todo_items
  # GET /todo_items.json
  def index
    @todo_items = @todo_list.todo_items.paginate(page: params[:page], per_page: 5)
  end

  # GET /todo_items/1
  # GET /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    # Only allow a list of trusted parameters through.
    def todo_item_params
      params.require(:todo_item).permit(:task_title, :due_date, :description, :done)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_item]) do |form| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% @todo_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input_field">
    <%= form.label :due_date %><br>
    <%= form.date_select :due_date %>
  </div>
  <div class="input_field">
    <%= form.label :task_title %><br>
    <%= form.text_field :task_title %>
  </div>
  <div class="input_field">
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <% if @todo_item.persisted? %>
    <div class="input_field">
      <%= form.label :done %><br>
      <%= form.check_box :done %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todo_list, @todo_item] %> |
<%= link_to 'Back', @todo_list %>

app/views/todo_items/index.html.erb
<h1>Todo Items</h1>

<% @todo_items.each do |todo_item| %>
  <div class="todo_item">
    <%= link_to "#{todo_item.due_date} - #{todo_item.task_title}", todo_item, class: "todo_item_link" %>
  </div>
<% end %>
<p />
%= will_paginate @todo_items %>
<p />

<%= link_to 'New Todo Item', new_todo_item_path %>

app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @todo_list %>

app/views/todo_items/show.html.erb
<div class="todo_item">
	<h1>
		<%= "#{@todo_item.task_title}" %>
	</h1>
	<h2>
		<%= "Due on: #{@todo_item.due_date}" %>
	</h2>
	<h3>
		<%= "Status: #{@todo_item.done ? "Done": "Not done"}" %>
	</h3>
	<p>
		<%= "#{@todo_item.description}" %>
	</p>

</div>
<p />

<%= link_to 'Edit Todo Item', edit_todo_list_todo_item_path(@todo_list, @todo_item) %> |
<%= link_to 'Delete Todo Item', [@todo_list, @todo_item], method: :delete, 
      data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', @todo_list %>