config/routes.rb
Rails.application.routes.draw do

  root :to => 'todo_lists#index'
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]

  get '/accounts' => "accounts#index", as: "accounts_path"
  get '/todo_lists' => "todo_lists#index", as: "todo_lists_path"
  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items, dependent: :destroy

  default_scope { order list_due_date: :asc}
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.paginate(page: params[:page], per_page: 5)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_item = @todo_list.todo_items.new
    @todo_item = @todo_list.todo_items.paginate(page: params[:page], per_page: 5)
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:list_name, :list_due_date)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |form| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% @todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input_field">
    <%= form.label :list_due_date %><br>
    <%= form.date_select :list_due_date %>
  </div>
  <div class="input_field">
    <%= form.label :list_name %><br>
    <%= form.text_field :list_name %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h1>Todo Lists</h1>

<% @todo_lists.each do |todo_list| %>
  <div class="todo_list">
    <span>
      <% if todo_list.todo_items.any? {|item| !item.done } %>
        <div class="not_done">
      <% else %>
        <div class="done">
      <% end %>
      <%= "#{todo_list.list_due_date}" %>
      </div>
    <%= "-  " %>
    <%= link_to "#{todo_list.list_name}", todo_list, class: "todo_list_link" %>
    </span>
  </div>
<% end %>
<p />
<%= will_paginate @todo_lists %>
<p />

<%= link_to 'New Todo List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<div class="todo_list">
	<h1>
		<%= "#{@todo_list.list_name}" %>
	</h1>
	<h2>
        <%= "List due date: #{@todo_list.list_due_date}" %>
	</h2>
</div>
<p />

<%= link_to 'Add Todo Item', new_todo_list_todo_item_path(@todo_list) %>

<% @todo_item.each do |todo_item| %>
  <div class="todo_items">
    <span>
    	<% if todo_item.done? %>
        	<div class="done">
      	<% else %>
        	<div class="not_done">
      	<% end %>
      	<%= "#{todo_item.due_date}" %>
      	</div>
    	<%= "-  " %>
    	<%= link_to "#{todo_item.task_title}", [@todo_list, todo_item], class: "todo_list_link" %>
    </span>
  </div>
<% end %>
<p />
<%= will_paginate @todo_item %>
<p />

<%= link_to 'Edit Todo List', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Delete Todo List', @todo_list, method: :delete, 
      data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back To Todo Lists', todo_lists_path %>