config/routes.rb
Rails.application.routes.draw do

  root :to => 'todo_lists#index'
  resources :todo_lists do
    resources :todo_items
  end

  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]

  get '/accounts' => "accounts#index", as: "accounts_path"
  get '/todo_lists' => "todo_lists#index", as: "todo_lists_path"
  get '/login' => "sessions#new", as: "login"
  delete '/logout' => "sessions#destroy", as: "logout"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validates :gender, inclusion: { in: %w(male female N/A), message: "Gender can only be 'male', 'female', or 'N/A'" }
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 20, less_than_or_equal_to: 100 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @account = current_user.account
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.account
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :gender, :age)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |form| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% @account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input_field">
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </div>
  <div class="input_field">
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </div>
  <div class="input_field">
    <%= form.label :gender %><br>
    <%= form.select :gender, ["male", "female", "N/A"] %>
  </div>
  <div class="input_field">
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Account Info</h1>

<h3>
  <strong>Name:</strong>
  <%= @account.first_name %>
  <%= @account.last_name %>
</h3>

<h3>
  <strong>Gender:</strong>
  <%= @account.gender %>
</h3>

<h3>
  <strong>Age:</strong>
  <%= @account.age %>
</h3>
<p />

<%= link_to 'Edit Account', edit_account_path(@account) %> |
<%= link_to 'Back to Home', todo_lists_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<h1>Account Info</h1>

<h3>
  <strong>Name:</strong>
  <%= @account.first_name %>
  <%= @account.last_name %>
</h3>

<h3>
  <strong>Gender:</strong>
  <%= @account.gender %>
</h3>

<h3>
  <strong>Age:</strong>
  <%= @account.age %>
</h3>
<p />

<%= link_to 'Edit Account', edit_account_path(@account) %> |
<%= link_to 'Back to Home', todo_lists_path %>